name = "FilteredGroupbyMacro"
uuid = "d46d16aa-1548-45e6-bb37-c0a3431c6626"
authors = ["Julius Krumbiegel"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1"
DataFrames = "0.20"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
